logging:
  level:
    org.zerock.finedu: DEBUG
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/finedu?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USER:finedu_user}
    password: ${MYSQL_PASSWORD:finedu_password}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-3.5-turbo-0125

server:
  port: ${SERVER_PORT:8082}
  address: 0.0.0.0

